### ISSUE TITLE
my_consumers in OneShotAWI

### ISSUE THREAD

**Issue by YueNing** [yasserfarouk/scml#13]
**Describe the bug**
There may be a problem with my_consumers in OneShotAWI.

**To Reproduce**
1. Create a SCMLOneShotWorld
2. agent.awi.my_consumers
3. See the result of agent which in self.level==0

**Expected behavior**
agent is 00MyB@0

The supplier of the agent (level 0) is the SELLER(SYSTEM), but the consumer of the agent is the agent in the next level (level 1, e.g. 02Gre@1, 03Gre@1), not the same level agent(level 0).

**Screenshots**
![bug.png](https://i.loli.net/2021/03/15/5naAE2YWwZkpHOS.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
- SCML: 0.3.3

**Comment by yasserfarouk** [comment]
reproduced and will be resolved today
