### ISSUE TITLE
GreedyOneShotAgent mismatch

### ISSUE THREAD

**Issue by jacksondc** [yasserfarouk/scml#30]
The code given [in the tutorials](http://www.yasserm.com/scml/scml2020docs/tutorials/02.develop_agent_scml2020_oneshot.html#greedy-oneshotagent) for GreedyOneShotAgent does not match the implementation in [scml.oneshot.agents.GreedyOneShotAgent](https://github.com/yasserfarouk/scml/blob/master/src/scml/oneshot/agents/greedy.py#L20).

The implementation in the scml package corresponds to what's labelled in the tutorial as "LearningGreedyAgent" (except without inheritance from AdaptiveGreedyAgent, so I suspect it might be broken).

Expected behavior: I'd think it would make the most sense to change the implementation of GreedyOneShotAgent to match what's in the tutorial, and maybe add an scml.oneshot.agents.LearningGreedyAgent as well.

**Comment by yasserfarouk** [comment]
@jacksondc Will temporarily close this issue. Please reopen it if the naming convention is still causing an issue for you. Please create a new issue if the behavior of GreedyOneShotAgent was broken

**Comment by yasserfarouk** [comment]
Great 👍 thanks
