### ISSUE TITLE
Exogenous contract quantity in OneShot can be greater than 10

### ISSUE THREAD

**Issue by dipplestix** [yasserfarouk/scml#37]
**Describe the bug**
In the AWI's state, the exogenous quantity of the contract isn't limited by n_lines

**To Reproduce**
```
from scml.oneshot import OneShotAWI
a = OneShotAWI(world, world.agents['02Ran@0'])
177
a.state()
177
OneShotState(exogenous_input_quantity=14, exogenous_input_price=126, exogenous_output_quantity=0, exogenous_output_price=0, disposal_cost=0.5649356894772987, shortfall_penalty=0.5808409998388839, current_balance=13011.819059385482)
```

**Expected behavior**
exogenous_input_quantity should be capped at 10

**Comment by yasserfarouk** [comment]
Thank you for raising this issue. I confirmed it. A bugfix will be pushed soon. Fortunately, what this causes is a general reduction of all scores of all agents in a systematic way as all agents are tested in all configurations so current tournament results are all valid.
