### ISSUE TITLE
Cant access to level, is_first_level, is_last_level and is_middle_level

### ISSUE THREAD

**Issue by umutcakan** [yasserfarouk/scml#49]
AWI does not contain related level information, (level, is_first_level, is_last_level, is_middle_level). It would be perfect if AWI could contain related information as presented in the documentation.

**Comment by yasserfarouk** [comment]
It is easy to get this info from the AWI:

- level -> awi.my_input_product
- is_first_level -> (awi.my_input_product == 0)
- is_last_level -> (awi.my_output_product == awi.n_products - 1)
