### ISSUE TITLE
OneShot tournaments cannot be run properly.

### ISSUE THREAD

**Issue by Takumu0221** [yasserfarouk/scml#53]
When I executed following OneShot tournaments, the created world had more than two processes like this figure.
This situation happened after I upgraded scml to ver0.4.6.

        results = anac2021_oneshot(
            competitors=tournament_types,
            non_competitors=tournament_types,
            n_configs=5,  # number of different configurations to generate
            n_competitors_per_world=None,
            n_runs_per_world=1,  # number of times to repeat every simulation (with agent assignment)
            n_steps=10,  # number of days (simulation steps) per simulation
            print_exceptions=True,
        )

![image](https://user-images.githubusercontent.com/74670690/124233832-3bac1f00-db4e-11eb-9659-3be7dc2a9010.png)

**Comment by yasserfarouk** [comment]
Thanks for the report. We will investigate it

**Comment by Takumu0221** [comment]
It worked fine. Thank you very much for your answer.
