### ISSUE TITLE
Negotiation request from a bankrupted agent

### ISSUE THREAD

**Issue by furkancanturk** [yasserfarouk/scml#64]
Negotiation requests might be received from bankrupted agents.

Here some information from logged data:
Negotiation request from: 05BCS@1 
Current partners (not bankrupted): ['SELLER', '02MMM@1', '04Dec@1']
Bankrupted agents: ['03BCS@1', '05BCS@1']

I use the last version of scml.
I've observed this bug several times and the bankrupted agent was BCS each time.

**Comment by yasserfarouk** [comment]
Hi @furkancanturk 
Thank you for reporting this issue. We pushed a hot fix (not well tested yet). Please upgrade to the latest version on github and let me know if you still face the same issue.

```bash
pip uninstall scml
pip install -U git+https://www.github.com/yasserfarouk/scml
```

**Comment by furkancanturk** [comment]
Thank you, I have not faced the issue on several runs.
