### ISSUE TITLE
OneShotSyncAgent timing issue 2: "step" called during "counter_all"

### ISSUE THREAD

**Issue by jacksondc** [yasserfarouk/scml#67]
I'm back with another one: in some negotiation rounds, OneShotSyncAgent's `step` method will get called during `counter_all`.

**To Reproduce**
```py
import datetime

class MySyncAgent(OneShotSyncAgent):
    in_counter_all = False

    def step(self):
        if self.in_counter_all:
            raise RuntimeError("uh-oh")
    
    @staticmethod
    def delay():
        """Tune this to take ~3s"""
        before = datetime.datetime.now()
        a = 0
        for i in range(100000000):
            a *= i
        after = datetime.datetime.now()
        print("delay time:", after - before)

    def counter_all(self, offers, states):
        self.in_counter_all = True
        self.delay()
        self.in_counter_all = False

        return {
            k: SAOResponse(ResponseType.REJECT_OFFER, v)
            for k, v in self.first_proposals().items()
        }

    def first_proposals(self):
        return  dict(zip(
                self.negotiators.keys(),
                (self.get_offer(neg_id) for neg_id in self.negotiators.keys())
        ))

    def get_offer(self, negotiator_id: str):
        ami = self.get_ami(negotiator_id)
        quantity_issue = ami.issues[QUANTITY]
        unit_price_issue = ami.issues[UNIT_PRICE]

        offer = [-1] * 3
        offer[QUANTITY] = quantity_issue.max_value
        offer[TIME] = self.awi.current_step
        offer[UNIT_PRICE] = unit_price_issue.max_value
        return offer
```

I tuned `delay` to take about 3 seconds. On my machine, this raises "RuntimeError: uh-oh" after a while.

**Expected behavior**
A round does not end while `counter_all` is in progress.

OS: Mac OS 10.14

**Comment by jacksondc** [comment]
scml version: 0.4.7, negmas version: 0.8.6

I think it's hitting the total negotiation time limit. I was adding up the times wrong and thinking it would be under the limit. I'm running with neg_step_time_limit=60, neg_time_limit=120, four agents. Each response takes ~4 seconds, so total time spent each round could be 160 seconds.

**Comment by jacksondc** [comment]
Closing this one too!

**Comment by jacksondc** [comment]
I have a related problem that I think cannot be explained by the timeout issue: `counter_all` gets called while a previous call to `counter_all` is still in progress. Furthermore, the sets of opponents it's responding to may in some cases be the same—e.g.:

1. counter_all is called with offers from opponents A and B
2. Before the first call returns, counter_all is called again with the same offers from A and B

To reproduce:
```py

class MySyncAgent(OneShotSyncAgent):
    in_counter_all = False
    offers: Dict[str, Tuple[int]] = {}
    
    def init(self):
        self.step_time = datetime.datetime.now()

    def step(self):
        self.step_time = datetime.datetime.now()
    
    @staticmethod
    def delay():
        """Tune this to take ~3s"""
        before = datetime.datetime.now()
        a = 0
        for i in range(100000000):
            a *= i
        after = datetime.datetime.now()
        print("delay time:", after - before)

    def counter_all(self, offers, states):
        if self.in_counter_all:
            raise RuntimeError("uh-oh! new offers: {}, previous offers: {}"
                .format(offers, self.offers))

        self.in_counter_all = True
        self.offers = offers
        self.delay()
        self.in_counter_all = False

        return {
            k: SAOResponse(ResponseType.REJECT_OFFER, v)
            for k, v in self.first_proposals().items()
        }

    def first_proposals(self):
        return  dict(zip(
                self.negotiators.keys(),
                (self.get_offer(neg_id) for neg_id in self.negotiators.keys())
        ))

    def get_offer(self, negotiator_id: str):
        ami = self.get_ami(negotiator_id)
        quantity_issue = ami.issues[QUANTITY]
        unit_price_issue = ami.issues[UNIT_PRICE]

        offer = [-1] * 3
        offer[QUANTITY] = quantity_issue.max_value
        offer[TIME] = self.awi.current_step
        offer[UNIT_PRICE] = unit_price_issue.max_value
        return offer
```

I ran with `try_agents([RandomOneShotAgent] * 2 + [MySyncAgent] * 2, n_agents_per_process=2)` and received

```
RuntimeError: uh-oh! new offers: {'00Ran@0': (1, 4, 18), '01Ran@0': (10, 4, 13)}, previous offers: {'00Ran@0': (1, 4, 18), '01Ran@0': (10, 4, 13)}
```

scml version 0.4.7, negmas version 0.8.6, python 3.7.3, Mac OS 10.14.6

**Comment by yasserfarouk** [comment]
We could reproduce the issue but seeing the exception is expected behavior. Here is how it goes:
- NegMAS creates a thread to call any method in an agent (or a negotiator) in order to enforce timeout conditions
- If the timeout passes, the thread should be killed. Unfortunately, there is no clean method to kill threads in python so sometimes the thread just continue running specially if it is CPU bound like yours.
- At the timeout, the control returns to NegMAS which advances all mechanisms allowing the agent to receive new offers. That is when you receive the second call.

I added a test file to check for this condition [here](https://github.com/yasserfarouk/scml/blob/master/tests/test_oneshot_sync.py)

You can see that when negmas is forced to use a single thread, the issue disappears.

This is not fully convincing to me as the negotiation should end when the timeout condition is reached. We will keep the issue open while investigating it in more details.

thanks
