### ISSUE TITLE
Negotiation requests received before self.before_step call

### ISSUE THREAD

**Issue by furkancanturk** [yasserfarouk/scml#72]
In test run for submission to the league, negatiation requests are received before my agent's before_step call. Is it ok?
I think before_step function should be called before any action in the tournament except init function.

**Comment by yasserfarouk** [comment]
If you are speaking about the oneshot game then it may be the case. I have to confirm but agents in oneshot do not have any choice regarding requesting negotiations or accepting them. Both are forced. The agent should not override on-negotiation-request() or respond-to-negotiation-request().

**Comment by furkancanturk** [comment]
No, it is std-collusion

**Comment by yasserfarouk** [comment]
In std/collusion, an agent can request a negotiation in its before-step() which means that its partner(s) may receive negotiation requests before their before-step() calls.
