### ISSUE TITLE
no running negotiations in SCML2020OneShotWorld when update to 0.3.3

### ISSUE THREAD

**Issue by YueNing** [yasserfarouk/scml#9]
**Describe the bug**
When scml is updated from 0.3.1 -> 0.3.3, there are no running negotiations during running of SCML2020OneShotWorld.

I have debug it, can not enter into while any(running) in the function negmas.World._step_negotiation.
In version 0.3.0, did not find this problem, whether something is needed to be considered in version 0.3.3?

**To Reproduce**
1. Generate SCML2020OneShotWorld, agent_types: RandomOneShotAgent
2. No error, but can not see negotiation behavior

**Expected behavior**
Could see negotiations between agents

**Screenshots**
![0.3.3.PNG](https://i.loli.net/2021/03/06/VLidoxIbQ9jntU5.png)
can not enter into while any(running)
![stats.PNG](https://i.loli.net/2021/03/06/Ogcvds9PNT14C6j.png)
after running of World, print the world.states, n_negotiations is always 0

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: firefox
 - Version: OS version 18.04

**Additional context**
- agent_types=[RandomOneShotAgent]
- n_processes=2
- n_agents_per_process=1
- n_lines=10
- n_steps=10

**Comment by yasserfarouk** [comment]
Thanks for the report. I noticed the issue and reproduced it. An update will be pushed after the weekend with a bug fix.

**Comment by YueNing** [comment]
`pip uninstall negmas`
`pip uninstall scml`
`pip install git+https://github.com/yasserfarouk/negmas.git`
` pip install git+https://github.com/yasserfarouk/scml.git`

then it works, thanks a lot.

**Comment by YueNing** [comment]
> Thanks for the report. I noticed the issue and reproduced it. An update will be pushed after the weekend with a bug fix.

`pip uninstall negmas`
`pip uninstall scml`
`pip install git+https://github.com/yasserfarouk/negmas.git`
` pip install git+https://github.com/yasserfarouk/scml.git`

then it works, thanks a lot.

**Comment by yasserfarouk** [comment]
solved
