### ISSUE TITLE
Partial list of agents scores

### ISSUE THREAD

**Issue by yasserfarouk** [yasserfarouk/scml#96]
### Discussed in https://github.com/yasserfarouk/scml/discussions/94

<div type='discussions-op-text'>

<sup>Originally posted by **eranhirs** May 15, 2022</sup>
After adding a few agents to the `competitors` list in `myagent.py` (from the skeleton), in the final table of agents I sometimes get a partial list.
Is it intentionally not showing all agents? I also sometimes get agents I don't have in my list, such as `SingleAgreementAspirationAgent`, where are they coming from?</div>

**Comment by snippet2021** [comment]
Now I have same issue after updating scml package yesterday.
This happens even when we run the template code.

**Comment by yasserfarouk** [comment]
Thank you for reporting. We will fix this asap. Hopefully the fix will be pushed by tomorrow. Sorry for the inconvenience.

**Comment by yasserfarouk** [comment]
@snippet2021 please upgrade SCML to 0.5.5 (negmas will be upgraded to 0.9.5) and if you are using SCML-agents or SCML-vis upgrade them too. I hope you will find that scores make sense now.

```bash
pip install -U scml scml-agents scml-vis
```
